### ISSUE TITLE
Pre-Release: Latest - Error

### ISSUE THREAD

**Issue by Rushmead** [WatchBeam/ftl-studio#1]
So i decided i wanted to try out this build of FTL Studio to test it. Found an issue where you cannot start streaming and it comes out with the following error 

> 09:14:25.856: rtmp-common.c: [initialize_output] Could not find service ''
> 09:14:25.885: Failed to initialize stream configuration: errno 1

Just thought i'd let you know!

**Comment by connor4312** [comment]
@NCommander
