### ISSUE TITLE
.dll missing?

### ISSUE THREAD

**Issue by SkippTekk** [WatchBeam/ftl-studio#11]
Hey man, i know this may sound stupid. but apparently i have VCRUNTIME140.dll missing. was this included or do i have to download it separately?

**Comment by SkippTekk** [comment]
Sorry! i forgot to include what version im talking about. Tachyon 2016-05-04 @sslivins

**Comment by sslivins** [comment]
This is part of the visual studio runtime.  I will statically link this in our next release but in the mean time checkout https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by SkippTekk** [comment]
Awesome! thanks, that works. then it fires off on another section that is required. 

libx264-148.dll

And also, i can't seem to get the http://client.obsremote.com/ working...

**Comment by sslivins** [comment]
that's strange...what version of Tachyon are you using?

**Comment by sslivins** [comment]
we dont use 264 so that fact that it wants that is strange...what sources are you trying to stream?

**Comment by sslivins** [comment]
ping me on twitter and I'll get you a new build to test out:  @AustinP_at_Beam

**Comment by ProbablePrime** [comment]
@SkippTekk Unfortunately obsremote is not supported in OBS Studio. As we use that as a base for Tachyon its also not supported here. You can track this issue over on the obs remote page at https://github.com/bilhamil/OBSRemote/issues/10
