### ISSUE TITLE
Better Instructions for Linux

### ISSUE THREAD

**Issue by tankerkiller125** [WatchBeam/ftl-studio#13]
It seems that on Ubuntu 16.04 ftl-studio (tachyon) does not install properly. Possibly because there is a ray-tracer lib with the same name in the Ubuntu Repo's.

**Comment by sslivins** [comment]
could you post the actual error from the console?

**Comment by tankerkiller125** [comment]
There are no errors in the console during install. But icons and/or a command for it never appear or exists.

**Comment by sslivins** [comment]
the dependencies for tachyon should be identical to those of OBS-Studio.  https://github.com/jp9000/obs-studio/wiki/Install-Instructions  If these do not resolve your issue please reopen this ticket

**Comment by xmxstudio** [comment]
this doesnt help
