### ISSUE TITLE
FindFTLSDK Failure

### ISSUE THREAD

**Issue by awilliamson** [WatchBeam/ftl-studio#15]
The current Linux Build script installs FTLSDK to /tmp/tachyon, yet the FindFTLSDK.cmake file will search in the final install location /opt/tachyon.

Either install the SDK system-wide, or change the Find to include the temporary location.

Had to run a manual `sudo make install` in the ftl-sdk intermediate directory. Whilst we're on oddities, isn't it strange to 're-download' the ftl-studio repo, within the build-scripts folder of the repo itself? A little bit recursive don't you think?

Apologies for being terse, but your own guidelines do state the nature of Open-Source is one of bluntness.

Kind Regards,
Ashley Williamson

EDIT - It also never finally moves itself to /opt/tachyon. Thus once you finally do compile the binary, it searches in the wrong directory for the locale information, resulting in errors.

**Comment by sslivins** [comment]
I appreciate the feedback and I completely understand your frustration.  Our objective was to get this out to our community as quickly as possible but that said the linux build scripts have a great deal of room for improvement and is something actively being worked on.  The ftl module will eventually become a submodule within the repo to simplify the install process.  ftl-studio is not redownloaded, only the submodules are.

**Comment by sslivins** [comment]
I have updated the build scripts to install directly to /opt/tachyon rather than the temp folder to avoid the problems you mentioned.

**Comment by xmxstudio** [comment]
sslivins.. can you share some knowledge/scripts/help getting this thing to compile on ubuntu 16.04?
