### ISSUE TITLE
Trying to run on Arch Linux

### ISSUE THREAD

**Issue by Xandaros** [WatchBeam/ftl-studio#16]
I just installed Tachyon using a script called `debtap`, which converts .deb files to Arch Linux packages. (You might want to consider providing a simple tarball with the binaries, since creating packages from .deb is prone to errors and your install instructions are a mess. And looking at the install scripts, I'm not even going to touch them.)

When trying to start it, I get the following:

```
tachyon: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by tachyon)
```

Some googling tells me that this is apparently because you depend on an outdated libcurl version.
If this is the case, please update to a newer version. Depending on old libraries, especially those doing cryptography, is a security risk.

**Comment by ghost** [comment]
LD_PRELOAD=/usr/lib/libcurl.so.3 tachyon

**Comment by Xandaros** [comment]
@sslivins You closed this issue. Did you update the libcurl version tachyon uses?
