### ISSUE TITLE
Unspecified Error when trying to stream.

### ISSUE THREAD

**Issue by Xial** [WatchBeam/ftl-studio#17]
Hello!
I was trying out Tachyon fir the first time, and I'm unable to stream. 

Reading through the log, I'm guessing there's some kind of audio-specific error.

I've attached the log below, in case it helps.

Suggestions? 

Thanks, 
Xial

> 14:33:35.925: CPU Name: AMD FX(tm)-6100 Six-Core Processor  
> 14:33:35.926: CPU Speed: 3293MHz
> 14:33:35.926: Physical Cores: 3, Logical Cores: 6
> 14:33:35.926: Physical Memory: 16341MB Total, 7293MB Free
> 14:33:35.926: Windows Version: 10.0 Build 10586 (revision: 0)
> 14:33:35.926: Aero is Enabled (Aero is always on for windows 8 and above)
> 14:33:35.946: OBS 1.0 (64bit, windows)
> 14:33:35.946: ---------------------------------
> 14:33:35.946: ---------------------------------
> 14:33:35.946: audio settings reset:
> 14:33:35.946:   samples per sec: 44800
> 14:33:35.946:   speakers:        2
> 14:33:35.948: ---------------------------------
> 14:33:35.948: Initializing D3D11..
> 14:33:35.948: Available Video Adapters: 
> 14:33:35.951:   Adapter 1: AMD Radeon R9 200 Series
> 14:33:35.951:     Dedicated VRAM: 2128769024
> 14:33:35.951:     Shared VRAM:    4272748544
> 14:33:35.951:     output 1: pos={0, 0}, size={1920, 1080}, attached=true
> 14:33:35.951:     output 2: pos={-1920, 0}, size={1920, 1080}, attached=true
> 14:33:35.951:     output 3: pos={1920, 85}, size={1600, 900}, attached=true
> 14:33:35.958: Loading up D3D11 on adapter AMD Radeon R9 200 Series (0)
> 14:33:35.975: D3D11 loaded sucessfully, feature level used: 45056
> 14:33:37.137: ---------------------------------
> 14:33:37.137: video settings reset:
> 14:33:37.137:   base resolution:   1920x1080
> 14:33:37.137:   output resolution: 1920x1080
> 14:33:37.137:   fps:               30/1
> 14:33:37.137:   format:            I420
> 14:33:37.140: ---------------------------------
> 14:33:37.143: Loading module: coreaudio-encoder.dll
> 14:33:37.144: [CoreAudio encoder]: Failed loading library 'CoreAudioToolbox.dll'
> 14:33:37.144: [CoreAudio encoder]: Couldn't load CoreAudio AAC encoder
> 14:33:37.144: ---------------------------------
> 14:33:37.145: Loading module: image-source.dll
> 14:33:37.145: ---------------------------------
> 14:33:37.154: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
> 14:33:37.154: ---------------------------------
> 14:33:37.156: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
> 14:33:37.156: ---------------------------------
> 14:33:37.157: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
> 14:33:37.157: ---------------------------------
> 14:33:37.158: Loading module: obs-browser.dll
> 14:33:37.158: Failed to load 'en-US' text for module: 'obs-browser.dll'
> 14:33:37.158: ---------------------------------
> 14:33:37.159: Loading module: obs-ffmpeg.dll
> 14:33:37.160: ---------------------------------
> 14:33:37.162: Loading module: obs-filters.dll
> 14:33:37.164: ---------------------------------
> 14:33:37.166: Loading module: obs-outputs.dll
> 14:33:37.166: ---------------------------------
> 14:33:37.167: Loading module: obs-transitions.dll
> 14:33:37.168: ---------------------------------
> 14:33:37.169: Loading module: obs-x264.dll
> 14:33:37.169: ---------------------------------
> 14:33:37.170: Loading module: rtmp-services.dll
> 14:33:37.171: ---------------------------------
> 14:33:37.172: Loading module: text-freetype2.dll
> 14:33:37.176: ---------------------------------
> 14:33:37.177: Loading module: win-capture.dll
> 14:33:37.178: load_graphics_offsets: Failed to start 'get-graphics-offsets32.exe'
> 14:33:37.178: ---------------------------------
> 14:33:37.178: Loading module: win-decklink.dll
> 14:33:37.189: No blackmagic support
> 14:33:37.189: Failed to start search for DeckLink devices
> 14:33:37.189: ---------------------------------
> 14:33:37.190: Loading module: win-dshow.dll
> 14:33:37.201: ---------------------------------
> 14:33:37.204: Loading module: win-mf.dll
> 14:33:37.204: [Media Foundation encoder]: Adding Media Foundation AAC Encoder
> 14:33:37.480: ---------------------------------
> 14:33:37.481: Loading module: win-wasapi.dll
> 14:33:37.487: =====================================================================
> 14:33:37.488: output 'adv_stream' (rtmp_output) created
> 14:33:37.489: output 'adv_ffmpeg_output' (ffmpeg_output) created
> 14:33:37.489: encoder 'streaming_h264' (obs_x264) created
> 14:33:37.491: AAC encoder bitrate mapping:
> 14:33:37.491:    32 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491:    64 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491:    96 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
> 14:33:37.491:   128 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
> 14:33:37.491:   160 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
> 14:33:37.491:   192 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
> 14:33:37.491:   224 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491:   256 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491:   288 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491:   320 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
> 14:33:37.491: encoder 'adv_aac0' (mf_aac) created
> 14:33:37.491: encoder 'adv_aac1' (mf_aac) created
> 14:33:37.491: encoder 'adv_aac2' (mf_aac) created
> 14:33:37.491: encoder 'adv_aac3' (mf_aac) created
> 14:33:37.491: Service '' not found
> 14:33:37.491: service 'default_service' (rtmp_common) created
> 14:33:37.493: All scene data cleared
> 14:33:37.493: ------------------------------------------------
> 14:33:37.538: WASAPI: Device '1 - M220VA (AMD High Definition Audio Device)' initialized
> 14:33:37.538: source 'Desktop Audio' (wasapi_output_capture) created
> 14:33:37.562: WASAPI: Device 'FrontMic (Realtek High Definition Audio)' initialized
> 14:33:37.562: source 'Mic/Aux' (wasapi_input_capture) created
> 14:33:37.562: source 'Trove' (window_capture) created
> 14:33:37.563: adding 22 milliseconds of audio buffering, total audio buffering is now 22 milliseconds
> 14:33:37.563: source 'Trovian' (scene) created
> 14:33:37.563: source 'Troev' (game_capture) created
> 14:33:37.566: source 'Main.display' (monitor_capture) created
> 14:33:37.566: source 'Scene' (scene) created
> 14:33:37.652: == Profiler Results =============================
> 14:33:37.652: run_program_init: 1803.91Â ms
> 14:33:37.652:  â”£OBSApp::AppInit: 3.013Â ms
> 14:33:37.652:  â”ƒ â”—OBSApp::InitLocale: 1.517Â ms
> 14:33:37.652:  â”—OBSApp::OBSInit: 1777.45Â ms
> 14:33:37.652:    â”£obs_startup: 1.411Â ms
> 14:33:37.652:    â”—OBSBasic::OBSInit: 1705.68Â ms
> 14:33:37.652:      â”£OBSBasic::InitBasicConfig: 0.514Â ms
> 14:33:37.652:      â”£OBSBasic::ResetAudio: 0.528Â ms
> 14:33:37.652:      â”£OBSBasic::ResetVideo: 1192.62Â ms
> 14:33:37.652:      â”£OBSBasic::InitOBSCallbacks: 0.019Â ms
> 14:33:37.652:      â”£OBSBasic::InitHotkeys: 0.072Â ms
> 14:33:37.653:      â”£obs_load_all_modules: 347.619Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(coreaudio-encoder.dll): 1.284Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(image-source.dll): 0.003Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-browser.dll): 0.092Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-ffmpeg.dll): 0.012Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-filters.dll): 0.022Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-outputs.dll): 0.008Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-transitions.dll): 0.01Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(obs-x264.dll): 0.004Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(rtmp-services.dll): 0.596Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(text-freetype2.dll): 4.328Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(win-capture.dll): 0.277Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(win-decklink.dll): 10.29Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(win-dshow.dll): 10.84Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(win-mf.dll): 276.056Â ms
> 14:33:37.653:      â”ƒ â”£obs_init_module(win-wasapi.dll): 0.013Â ms
> 14:33:37.653:      â”ƒ â”—reset_win32_symbol_paths: 5.486Â ms
> 14:33:37.653:      â”£OBSBasic::ResetOutputs: 3.772Â ms
> 14:33:37.653:      â”£OBSBasic::CreateHotkeys: 0.044Â ms
> 14:33:37.653:      â”£OBSBasic::InitService: 0.274Â ms
> 14:33:37.653:      â”£OBSBasic::InitPrimitives: 0.636Â ms
> 14:33:37.653:      â”—OBSBasic::Load: 76.648Â ms
> 14:33:37.653: =================================================
> 14:33:37.858: Update check: last known remote version is 2016.4.4.0
> 14:33:42.294: rtmp-common.c: [initialize_output] Could not find service ''
> 14:33:42.296: got stream key: 7QQQQSSSSI89b------------hax6942
> 14:33:42.296: got channel id: ABCDE
> 14:33:42.297: test ABCDE FGHIJ
> 14:33:42.502: [libftl] ingest accepted our paramteres
> 14:33:42.502: FFMPEG Version: 57.35.100
> 14:33:42.502: 
> 14:33:42.502: AV Codec configurations --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
> 14:33:42.502: 
> 14:33:42.546: Failed to open audio codec: Invalid argument
> 14:33:42.546: ffmpeg_data_init failed
> 14:33:42.557: ==== Recording Stop ================================================

**Comment by sslivins** [comment]
the above issue is caused by the wrong audio setting:

14:33:42.546: Failed to open audio codec: Invalid argument
14:33:42.546: ffmpeg_data_init failed

please go into settings->audio->sample rate and change it from 44.1khz to 48khz and try again
