### ISSUE TITLE
api-ms-win-core-libraryloader-l1-2-0.dll missing

### ISSUE THREAD

**Issue by krakaen** [WatchBeam/ftl-studio#19]
Just tried to install the new v1.0 and it gives me api-ms-win-core-libraryloader-l1-2-0.dll

I was able to get the others to work fine...

can't seem to find where that dll is coming from,

any idea?

**Comment by cros1625** [comment]
This is a known issue at the moment and we're looking into it. What OS are you running? 

Also, in the future, it would be best to send support questions directly to https://beam.pro/contact so we can track them.

cros1625
Beam.pro Support

**Comment by sslivins** [comment]
please try v1.0.1 in the releases tab

**Comment by sslivins** [comment]
this issues should be resolved with v1.0.1 and v1.1:  https://github.com/WatchBeam/tachyon/releases/tag/v1.1.0
