### ISSUE TITLE
entry point not found?

### ISSUE THREAD

**Issue by shufunk** [WatchBeam/ftl-studio#20]
May be nothing but this pops up when launching 1.0.1 

https://surl.im/i/xyj6x

Other then that the program fully loads on Windows 10 Pro with no problems. Too tired to do a test stream and will do one hopefully tomorrow. Just wanted share this and if it's nothing then close this if you feel the need.

**Comment by sslivins** [comment]
thanks for the feedback.  this error is benign as you suspected however it shouldn't happen either.  can you try uninstalling tachyon, then going to c:\program files (x86)\Tachyon and make sure the folder either does not exist or that it's empty.  if not please completely remove it and try to install again.  I suspect the uninstall didnt work

**Comment by shufunk** [comment]
I used iobituninstaller this time and it found files left behind and removed them all. After the reinstall no errors! Thanks for the help
