### ISSUE TITLE
postproc-54.dll not found

### ISSUE THREAD

**Issue by jordanbaucke** [WatchBeam/ftl-studio#22]
Downloaded the latest dependencies mentioned in the explanation (https://github.com/WatchBeam/tachyon/blob/ftl-ffmpeg/build_scripts/how_to_build_on_windows.txt), this last statement copying the postproc-54.dll, fails, as this file was not in the build dependencies downloaded from: http://code.fosshub.com/OBS/downloads (dependencies2015.zip)

Manually grabbed a copy of it from FFMPEG, still failing - can't figure out if it's a file-permissions error or? 

`copy %coredeps%\win64\bin\postproc-54.dll rundir\Release\bin\64bit` file not found.

**Comment by sslivins** [comment]
Sorry, this is my fault, that is the obs link which is missing support for vp8/opus etc.  I have posted my files that i built:  https://github.com/WatchBeam/tachyon/releases/download/v1.0.1/dependencies2015.zip

let me know if you are having any other issues.

**Comment by sslivins** [comment]
there is another release out now: https://github.com/WatchBeam/tachyon/releases/tag/v1.1.0  

I'd love to get your feedback on the build process and any issues you hit.

**Comment by jordanbaucke** [comment]
Thanks @sslivins are you active on gitter room or irc?
