### ISSUE TITLE
Build fails locating Visual.obj

### ISSUE THREAD

**Issue by jordanbaucke** [WatchBeam/ftl-studio#24]
Using new dependencies files at https://github.com/WatchBeam/tachyon/releases/tag/v1.1.0,

I also installed Qt, and ffmpeg (static version), added to path, and tested `~$ ffmpeg` correctly runs, so I ran.

`PS C:\Users\jordan-windows-10\Documents\Visual Studio 2015\tachyon\build_scripts> .\build_tachyon_windows_vs.bat`

The build process gets much further along, but gets a fatal error:

```
"C:\Users\jordan-windows-10\Documents\Visual Studio 2015\tachyon\build_scripts\ALL_BUILD.vcxproj" (default target) (1)
->
"C:\Users\jordan-windows-10\Documents\Visual Studio 2015\tachyon\build_scripts\plugins\obs-ffmpeg\obs-ffmpeg.vcxproj" (
default target) (21) ->
(Link target) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Users\jordan-windows-10\Documents\Visual.obj' [C:\Users\jordan
-windows-10\Documents\Visual Studio 2015\tachyon\build_scripts\plugins\obs-ffmpeg\obs-ffmpeg.vcxproj]

    1008 Warning(s)
    1 Error(s)

Time Elapsed 00:03:11.18s
```

Not sure why I would having this relative path to `Visual.obj` in my `\Documents` directory?

**Comment by sslivins** [comment]
I'm on gitter if you prefer that: https://gitter.im/MCProHosting/beam-dev

you can probably use the stock ffmpeg libraries as long as they have support for libvpx and opus (I believe they do).  Currently the bat file expects them in c:\beam\tachyon_deps but this appears to be unrelated to the issue you have above.  I suspect the space in the directory name is causing problems.  my suggestions would be to create a folder in c:\tachyon and then checkout the repo in there and try again

**Comment by sslivins** [comment]
@jordanbaucke any other concerns or can i close this ticket?

**Comment by jordanbaucke** [comment]
@sslivins nope! should be good thanks!
