### ISSUE TITLE
Tachyon keeps crashing on start

### ISSUE THREAD

**Issue by ZoefyC** [WatchBeam/ftl-studio#25]
Hi, 
I don't know why, but whenever I start up Tachyon, it crashes and says:

> Woops, OBS crashed!

This is the crashlog: http://pastebin.com/04b327n3

I hope you can help :)
~Zoe_

**Comment by cros1625** [comment]
Looks like the crash is happening in the transitions. Can you send us the transitions you have installed in OBS Studio and we will look into adding them into Tachyon to avoid the crash in the future.

Contact us directly at https://beam.pro/contact

**Comment by cros1625** [comment]
For those who run into similar issues in the logs, this error seems to come from not uninstalling / not deleting the Tachyon folder before installing the new version.

**Solution:**
Uninstall Tachyon and delete the Tachyon folder at C:\Program Files (x86), then download and install the latest version from here https://github.com/WatchBeam/tachyon/releases

If it still doesn't work, send us a support ticket at https://beam.pro/contact
