### ISSUE TITLE
.dll Files Missing

### ISSUE THREAD

**Issue by LotG-Catherine** [WatchBeam/ftl-studio#27]
I've downloaded Tachyon, but it needed a .dll.  I looked up the .dll, found where I could download and install it.  So, I did. Removed the old Tachyon. Installed the C++. Installed Tachyon.  Still have the error.
It repeats 3-5 times before closing out.

![tachyon64 exe system error](https://cloud.githubusercontent.com/assets/19659259/15662011/88064796-26b2-11e6-8b11-16061096d2bd.jpg)

Thanks,
Catherine

**Comment by sslivins** [comment]
Hi Catherine,

This dll is part of the visual c++ Redistributable.  The release install guide covers where this can be downloaded https://github.com/WatchBeam/tachyon/releases/download/v1.1.0/InstallGuide-win-linux-mac.-v1.1.txt however I have included this below for your convenience.  https://www.microsoft.com/en-us/download/details.aspx?id=48145
please let me know if this does not resolve your issue.

**Comment by sslivins** [comment]
Hi Catherine,

Im very sorry, i see in the picture above you do have what looks be the the v c++ redistribute.  The filename isnt the standard name from the link I provided above so I'm wondering if it's a repackaged version?  I would suggest trying the link above.  This really should resolve your issue, if it does not please let me know what version of windows you are running.

**Comment by LotG-Catherine** [comment]
That seems to have fixed the issue.  Tachyon initially crashed, but I ran
the install .exe again and the program come up.

However, once I grabbed the stream key off the FTL setup dialog and got
things looking good on the preview, I ran into "An unspecified error
occurred while recording"?

Any thoughts?

Thanks,
Catherine

**Comment by sslivins** [comment]
can you post the last log file?  you can either get it from tachyon directly or past this into windows explorer to get to the logs folder:  %appdata%\obs-studio\logs

also look at the settings, audio needs to be at 48khz, video format should be i420 (despite to warning)

**Comment by LotG-Catherine** [comment]
Sure.  I attached/dropped in the text log.

Catherine

On Mon, May 30, 2016 at 11:25 PM, sslivins notifications@github.com wrote:

> can you post the last log file? you can either get it from tachyon
> directly or past this into windows explorer to get to the logs folder:
> %appdata%\obs-studio\logs
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/WatchBeam/tachyon/issues/27#issuecomment-222589807,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASv5-0dZQrz-WKQe_2R2ft9ouVGP2Frsks5qG7hPgaJpZM4IqJDD
> .

23:33:13.861: CPU Name: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
23:33:13.861: CPU Speed: 3500MHz
23:33:13.861: Physical Cores: 4, Logical Cores: 4
23:33:13.861: Physical Memory: 24460MB Total, 17967MB Free
23:33:13.861: Windows Version: 10.0 Build 10586 (revision: 0)
23:33:13.861: Aero is Enabled (Aero is always on for windows 8 and above)
23:33:13.871: OBS 1.0.1 (64bit, windows)
23:33:13.871: ---------------------------------
23:33:13.871: ---------------------------------
23:33:13.871: audio settings reset:
23:33:13.871:   samples per sec: 44100
23:33:13.871:   speakers:        2
23:33:13.872: ---------------------------------
23:33:13.872: Initializing D3D11..
23:33:13.872: Available Video Adapters: 
23:33:13.873:   Adapter 1: AMD Radeon R9 200 Series
23:33:13.873:     Dedicated VRAM: 2123243520
23:33:13.873:     Shared VRAM:    4234475520
23:33:13.873:     output 1: pos={0, 0}, size={1920, 1080}, attached=true
23:33:13.873:     output 2: pos={-1440, 80}, size={1440, 900}, attached=true
23:33:13.873:   Adapter 2: Intel(R) HD Graphics 4600
23:33:13.873:     Dedicated VRAM: 117964800
23:33:13.873:     Shared VRAM:    4234475520
23:33:13.875: Loading up D3D11 on adapter AMD Radeon R9 200 Series (0)
23:33:13.883: D3D11 loaded sucessfully, feature level used: 45056
23:33:14.293: ---------------------------------
23:33:14.293: video settings reset:
23:33:14.293:   base resolution:   1920x1080
23:33:14.293:   output resolution: 1280x720
23:33:14.293:   fps:               30/1
23:33:14.293:   format:            NV12
23:33:14.295: ---------------------------------
23:33:14.295: Loading module: coreaudio-encoder.dll
23:33:14.296: [CoreAudio encoder]: Failed loading library 'CoreAudioToolbox.dll'
23:33:14.296: [CoreAudio encoder]: Couldn't load CoreAudio AAC encoder
23:33:14.296: ---------------------------------
23:33:14.296: LoadLibrary failed for '../../obs-plugins/64bit/d3dcompiler_43.dll', error: 193
23:33:14.296: Module '../../obs-plugins/64bit/d3dcompiler_43.dll' not found
23:33:14.296: ---------------------------------
23:33:14.297: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/d3dcompiler_47.dll' not found, loading of module failed
23:33:14.297: ---------------------------------
23:33:14.297: Loading module: image-source.dll
23:33:14.297: ---------------------------------
23:33:14.300: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
23:33:14.300: ---------------------------------
23:33:14.301: Loading module: obs-browser.dll
23:33:14.301: Failed to load 'en-US' text for module: 'obs-browser.dll'
23:33:14.301: ---------------------------------
23:33:14.301: Loading module: obs-ffmpeg.dll
23:33:14.301: ---------------------------------
23:33:14.302: Loading module: obs-filters.dll
23:33:14.302: ---------------------------------
23:33:14.302: Loading module: obs-outputs.dll
23:33:14.302: ---------------------------------
23:33:14.302: Loading module: obs-transitions.dll
23:33:14.303: ---------------------------------
23:33:14.303: Loading module: obs-x264.dll
23:33:14.303: ---------------------------------
23:33:14.303: Loading module: rtmp-services.dll
23:33:14.304: ---------------------------------
23:33:14.304: Loading module: text-freetype2.dll
23:33:14.305: ---------------------------------
23:33:14.305: Loading module: win-capture.dll
23:33:14.306: ---------------------------------
23:33:14.306: Loading module: win-decklink.dll
23:33:14.309: No blackmagic support
23:33:14.309: Failed to start search for DeckLink devices
23:33:14.309: ---------------------------------
23:33:14.309: Loading module: win-dshow.dll
23:33:14.311: ---------------------------------
23:33:14.312: Loading module: win-mf.dll
23:33:14.312: [Media Foundation encoder]: Adding Media Foundation AAC Encoder
23:33:14.459: ---------------------------------
23:33:14.459: Loading module: win-wasapi.dll
23:33:14.460: =====================================================================
23:33:14.460: output 'adv_stream' (rtmp_output) created
23:33:14.460: output 'adv_ffmpeg_output' (ffmpeg_output) created
23:33:14.460: encoder 'streaming_h264' (obs_x264) created
23:33:14.460: AAC encoder bitrate mapping:
23:33:14.460:    32 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460:    64 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460:    96 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
23:33:14.460:   128 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
23:33:14.460:   160 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
23:33:14.460:   192 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
23:33:14.460:   224 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460:   256 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460:   288 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460:   320 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
23:33:14.460: encoder 'adv_aac0' (mf_aac) created
23:33:14.460: encoder 'adv_aac1' (mf_aac) created
23:33:14.460: encoder 'adv_aac2' (mf_aac) created
23:33:14.460: encoder 'adv_aac3' (mf_aac) created
23:33:14.461: service 'default_service' (rtmp_common) created
23:33:14.463: All scene data cleared
23:33:14.463: ------------------------------------------------
23:33:14.477: WASAPI: Device 'Speakers (2- Logitech G930 Headset)' initialized
23:33:14.477: source 'Desktop Audio' (wasapi_output_capture) created
23:33:14.483: WASAPI: Device 'Microphone (2- Logitech G930 Headset)' initialized
23:33:14.483: source 'Mic/Aux' (wasapi_input_capture) created
23:33:14.520: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
23:33:14.540: source 'Papyrus Wallpaper' (image_source) created
23:33:14.566: source 'Thanks for watching v2' (text_ft2_source) created
23:33:14.578: source 'LotG playing Pathfinder' (text_ft2_source) created
23:33:14.579: source 'KingsTears Game Inn' (scene) created
23:33:14.590: source 'LotG_Jane' (text_ft2_source) created
23:33:14.633: source 'Ladies on the Game Channel is offline' (image_source) created
23:33:14.634: source 'LotG Channel is offline' (scene) created
23:33:14.645: source 'KingsTears/Catherine' (text_ft2_source) created
23:33:14.663: source 'Ladies on the Game' (text_ft2_source) created
23:33:14.663: source 'ESO Wallpaper' (image_source) created
23:33:14.663: source 'Desktop & Webcam' (scene) created
23:33:14.663: source 'LotG Be Right Back' (scene) created
23:33:14.664: source 'LotG Game & Webcam' (scene) created
23:33:14.664: source 'LotG Will be playing soon' (scene) created
23:33:14.665: source 'Display Capture' (monitor_capture) created
23:33:14.665: source 'Elder Scrolls Online' (window_capture) created
23:33:14.665: source 'Window Capture' (window_capture) created
23:33:14.708: source 'Ladies on the Game Will be playing soon Green' (image_source) created
23:33:14.751: source 'Ladies on the Game Will be playing soon Pink' (image_source) created
23:33:14.793: source 'Ladies on the Game Will be right back Green' (image_source) created
23:33:14.837: source 'Ladies on the Game Will be right back Pink' (image_source) created
23:33:14.837: source 'Logitech C130 Camera' (dshow_input) created
23:33:14.838: source 'Logitech C130 Camera' enabled push-to-talk
23:33:14.845: source 'LotG StreamJar' (browser_source) created
23:33:14.846: source 'Worms' (window_capture) created
23:33:14.846: [Media Source 'BRB Music']: invalid audio_buffer_size 1
23:33:14.846: [Media Source 'BRB Music']: invalid audio_buffer_size 1
23:33:14.846: [Media Source 'BRB Music']: settings:
23:33:14.846:   input:                   D:/Users/Owner/Documents on D/~Streaming/Sounds/Artemis.wav
23:33:14.846:   input_format:            (null)
23:33:14.846:   is_looping:              yes
23:33:14.846:   is_forcing_scale:        yes
23:33:14.846:   is_hw_decoding:          yes
23:33:14.846:   is_clear_on_media_end:   yes
23:33:14.846:   restart_on_activate:     yes
23:33:14.846: [Media Source 'BRB Music']: advanced settings:
23:33:14.846:   audio_buffer_size:       1
23:33:14.846:   video_buffer_size:       1
23:33:14.846:   frame_drop:              AVDISCARD_DEFAULT
23:33:14.846: source 'BRB Music' (ffmpeg_source) created
23:33:14.846: source 'Game Capture' (game_capture) created
23:33:14.857: ---------------------------------
23:33:14.857: [DShow Device: 'Logitech C130 Camera'] settings updated: 
23:33:14.857:   video device: Logitech HD Webcam C310
23:33:14.857:   video path: \?\usb#vid_046d&pid_081b&mi_00#6&47e784b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
23:33:14.857:   resolution: 1280x720
23:33:14.857:   fps: 30.00 (interval: 333333)
23:33:14.857:   format: I420
23:33:14.875: == Profiler Results =============================
23:33:14.875: run_program_init: 1031.42 ms
23:33:14.875:  ┣OBSApp::AppInit: 1.834 ms
23:33:14.875:  ┃ ┗OBSApp::InitLocale: 0.825 ms
23:33:14.875:  ┗OBSApp::OBSInit: 1024.76 ms
23:33:14.875:    ┣obs_startup: 0.771 ms
23:33:14.875:    ┗OBSBasic::OBSInit: 1003.56 ms
23:33:14.875:      ┣OBSBasic::InitBasicConfig: 0.275 ms
23:33:14.875:      ┣OBSBasic::ResetAudio: 0.221 ms
23:33:14.875:      ┣OBSBasic::ResetVideo: 422.723 ms
23:33:14.875:      ┣OBSBasic::InitOBSCallbacks: 0.008 ms
23:33:14.875:      ┣OBSBasic::InitHotkeys: 0.034 ms
23:33:14.875:      ┣obs_load_all_modules: 165.508 ms
23:33:14.875:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 0.288 ms
23:33:14.875:      ┃ ┣obs_init_module(image-source.dll): 0.002 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-browser.dll): 0.035 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.006 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-filters.dll): 0.006 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-outputs.dll): 0.003 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-transitions.dll): 0.004 ms
23:33:14.875:      ┃ ┣obs_init_module(obs-x264.dll): 0.001 ms
23:33:14.875:      ┃ ┣obs_init_module(rtmp-services.dll): 0.19 ms
23:33:14.875:      ┃ ┣obs_init_module(text-freetype2.dll): 1.017 ms
23:33:14.875:      ┃ ┣obs_init_module(win-capture.dll): 0.126 ms
23:33:14.875:      ┃ ┣obs_init_module(win-decklink.dll): 2.604 ms
23:33:14.875:      ┃ ┣obs_init_module(win-dshow.dll): 1.408 ms
23:33:14.875:      ┃ ┣obs_init_module(win-mf.dll): 146.973 ms
23:33:14.875:      ┃ ┣obs_init_module(win-wasapi.dll): 0.005 ms
23:33:14.875:      ┃ ┗reset_win32_symbol_paths: 0.358 ms
23:33:14.875:      ┣OBSBasic::ResetOutputs: 0.413 ms
23:33:14.875:      ┣OBSBasic::CreateHotkeys: 0.169 ms
23:33:14.875:      ┣OBSBasic::InitService: 0.09 ms
23:33:14.875:      ┣OBSBasic::InitPrimitives: 0.267 ms
23:33:14.875:      ┗OBSBasic::Load: 392.505 ms
23:33:14.875: =================================================
23:33:15.183: Update check: last known remote version is 2016.4.4.0
23:33:15.249: adding 23 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
23:33:16.528: [game-capture: 'Game Capture'] attempting to hook process: eso.exe
23:33:16.538: [game-capture: 'Game Capture'] d3d11 memory capture successful
23:33:19.213: ingest location blank
23:33:19.218: ==== Recording Stop ================================================

**Comment by sslivins** [comment]
audio is set to 44.1, try changing that to 48 and see if that fixes the crash

23:33:13.871: audio settings reset:
23:33:13.871:   samples per sec: 44100
23:33:13.871:   speakers:        2

**Comment by LotG-Catherine** [comment]
I set the audio to 48, exited, but no joy.  Just to be completest, I took a
look at the devices and realized what the 2 setting was for, and updated
the sound to go to my headset.
Then, I checked push to talk or mute as appropriate.  Exited, reloaded, and
got a quick test stream out.
Everything is GREEN. Like there's a green filter on the video.

Catherine

**Comment by sslivins** [comment]
the green is the video format, needs to be i420, not NV

**Comment by sslivins** [comment]
were you able to fix the green issue with that suggestion?

**Comment by LotG-Catherine** [comment]
OK. I switched to the I420; got a nasty looking warning about CPU usage,
but it streams alright.  Takes about 14 seconds to load to Beam (and back
to my browser) but it's only about 4s round trip after that.  Not too
shabby, and it seems quicker than the standard.

So, it's been tested live, everything seems good.  We'll be running FTL
tonight for our stream.

Thanks for helping me out, especially in the middle of the night.  Never
expected that, thanks.
Catherine

**Comment by sslivins** [comment]
closing as resolved
