### ISSUE TITLE
Provide Mac DMGs

### ISSUE THREAD

**Issue by encodedfox** [WatchBeam/ftl-studio#3]
Noticed that no Mac DMG packages were being made on this obs-studio for and improvement.  :)

This should be already doable using `cmake .. && make package` in the current Makefile since obs-studio (upstream) has this baked in.  I'm working to build this for people on Macs and found it would be very useful to not need to build it myself.  This can be prone to errors.

Thanks!

**Comment by FireBall1725** [comment]
Since i ended up making this on a mac, before you make package, you will need to edit the mac stuff, because it thinks the executable is still obs, where it is now tachyon.

**Comment by sslivins** [comment]
mac dmg package now available via release tab
