### ISSUE TITLE
Recommened server gives no response.

### ISSUE THREAD

**Issue by Khimah** [WatchBeam/ftl-studio#30]
I've tried streaming using Tachyon making sure everything is as it should but for some reason the server I need to use just doesn't do anything.  If a switch over to the California server it will start streaming but it ends up being laggy.  My recommended server is Dallas, TX.  If it helps any, my location I'm in Mississippi.

**Comment by sslivins** [comment]
how long ago did you attempt to connect to dallas?  what version of tachyon are you using?

**Comment by Khimah** [comment]
I just wrapped up a stream using OBS with the Dallas server.  I'm using version 1.2.6 of Tachyon.  I intend to try it again on my next stream.

**Comment by Khimah** [comment]
Okay just to update I attempted it again and even reset my stream key but still can't seem to reach the Dallas server through Tachyon.  I'm not sure what else I can try as of now so any advice will be helpful :)

**Comment by sslivins** [comment]
if you can give me the first part of your stream key, i can track down what happened on the dallas ingest...might be best to sent this via dm on gitter

**Comment by Khimah** [comment]
Not sure how much of the first part you need but the first few numbers are 45707.  Currently using OBS just fine through Dallas but for some reason Tachyon doesn't like it.

**Comment by sslivins** [comment]
your stream has a significant amount of packet loss.  what bitrate are you trying to stream at?  i would suggest trying something lower to see what works....i can tune your channel a bit also but lets try a lower bitrate first

**Comment by Khimah** [comment]
I was set to 2500 for Tachyon.  I was told it was recommended for it.  I usually stream at a higher bit rate for OBS.

**Comment by sslivins** [comment]
2500 is perfectly fine but for the purposes of this test i'd like you to try 1500, the resolution doesnt matter that much for the purposes of the test

**Comment by Khimah** [comment]
Okay I'll give it a shot

**Comment by Khimah** [comment]
Okay running at 1500 I did get the Dallas server to pick up but the video is unstable.  Audio is coming through fine.

**Comment by sslivins** [comment]
i would recommend a newer version of tachyon, 1.2.x are currently pre-released but stable and will be official very soon.  They have lost packet recovery to help with small amounts of intermittent packetloss which can adversely effect the experience
