### ISSUE TITLE
Building FTL-Express asking for GitHub Login

### ISSUE THREAD

**Issue by Gol-D-Ace** [WatchBeam/ftl-studio#39]
Hi.

I'm currently trying to build Tachyon.

It's now asking for an GitHub Login for cloning FTL-Express
![02-08-2016_18 39 48](https://cloud.githubusercontent.com/assets/5058319/17336901/97227730-58e0-11e6-9d2e-fba5e7f2ee91.png)

**Comment by sslivins** [comment]
Hi, Sorry but that repo is currently private.  I hope to make it public soon.  This is one of the reasons this release is still marked as a pre-release.  I can provide you the windows binary if you'd like or you can grab it from the installer

**Comment by Gol-D-Ace** [comment]
Would that one use the h264 ftl?
Only reason why I'm trying to build this currently.

**Comment by sslivins** [comment]
ftl-express is agnostic to the video codec so it will work with either vp8
or h264

**Comment by Gol-D-Ace** [comment]
>  I can provide you the windows binary if you'd like

Would that one use h264?
I saw that #ifdef got added for deciding between vp8 or h264

**Comment by sslivins** [comment]
yes, at the moment you will need to manually define that for it to use
H.264, you can just add it to the .c file.  that is the only place that
needs it.  alternatively i can provide you an alpha release of everything
already built into an installer that uses h.264

**Comment by Gol-D-Ace** [comment]
> alternatively i can provide you an alpha release of everything already built into an installer that uses h.264

That would be very nice of you.

**Comment by sslivins** [comment]
here you go:

https://dl.dropboxusercontent.com/u/20701844/Tachyon_Installer_1.3.3-h264-alpha.exe

you should only contact me here for support as our support team is not
familiar with it yet.  Also keep in mind that h.264 webrtc support is still
somewhat limited.  users trying to view your stream must have chrome v52 or
later (it is possible with v50 and v51 but they need to set a flag before
running it which is complicated for most people)  Firefox shouldnt be an
issue, they have supported H.264 for a while.  other browsers are unlikely
to work at all but are untested.

**Comment by YaLTeR** [comment]
How do I go about getting ftl-express for Linux?

**Comment by SilverCory** [comment]
Bumping for Linux.

**Comment by Maximilian-Reuter** [comment]
No point in building tachyon. The real project being worked on is this 

https://github.com/WatchBeam/obs-studio-ftl/tree/ftl

needs u also to build the sdk.

**Comment by sslivins** [comment]
My apologies for not having a linux build available.  In the meantime i have posted the ftl-express binary for linux here: https://github.com/WatchBeam/tachyon/releases/download/v1.2.14/ftl-express

**Comment by jacobmischka** [comment]
So wait, sorry, what am I supposed to do with this ftl-express binary? I'm a bit confused between tachyon, obs-studio-ftl, and ftl-express, what am I supposed to do to get ftl working on Linux?
