### ISSUE TITLE
Version 2016 04 02

### ISSUE THREAD

**Issue by SkippTekk** [WatchBeam/ftl-studio#4]
Won't let me save the location of where i want to stream.

Location wanted: Toronto
Location stuck/Default: Brazil (San Paulo)

Hot keys for Starting stream not working.
Start: CTRL- F2
Stop: CTRL - F3

**Comment by NCommander** [comment]
The location problem will be fixed in the next update. As for the hot keys, use the start recording/stop recording ones. For the time being, I haven't fixed all the references as internally Tachyon uses the "start recording' code path.
