### ISSUE TITLE
1.2.11 'Start Streaming' noop - ingest hang

### ISSUE THREAD

**Issue by benderisgo** [WatchBeam/ftl-studio#42]
Version is 1.2.11 on win10  x64 insider slow ring & Win10 x64 current:

'Start Streaming' does nothing, no log output.  I get the same results on both machines. 
The following is output from changing ingress server to any choice in the list which then results in a crash.

01:11:28.598: got channel id: 172698
01:11:28.598: test 172698 172699
01:11:39.118: Last log entry repeated for 601 more lines
01:11:39.118: test ingest-mel.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-sao.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-tor.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-ams.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-lon.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-fra.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-dal.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-sjc.beam.pro ingest-sea.beam.pro
01:11:39.118: test ingest-sea.beam.pro ingest-sea.beam.pro
01:11:53.871: Last log entry repeated for 853 more lines
01:11:53.871: encoder 'streaming_h264' destroyed
01:11:53.871: encoder 'Track4' destroyed
01:11:53.871: encoder 'Track3' destroyed
01:11:53.871: encoder 'Track2' destroyed
01:11:53.871: encoder 'Track1' destroyed
01:11:53.871: output 'adv_stream' destroyed
01:11:53.871: output 'adv_ffmpeg_output' destroyed

**Comment by Maximilian-Reuter** [comment]
Yeah I can support this! Happened to me yesterday, where for some reason the EU Frankfurt ingest server stopped working. Took me hours to try out another ingest server because the log isn't showing anything related to that issue

**Comment by Scrxtchy** [comment]
Getting this issue as well.
Clicking the start button does nothing, although if my streamkey is not input, an error dialog is displayed.
Was testing Melbourne, Austraila, my closest ingest. Also had similiar outcome on Washington DC.
Was able to connect fine to Brazil, and that was when I got a popup to allow Tachyon through my firewall.

I am running Windows 10 Pro Insider build 14901.rs_prelease.160805-1700

Appended:
Even though 'starting stream' button does not work, changing config while in this state causes the program to Hang

Double Appended:
Got it working for my ingest

My basic.ini file looks like this

```
[General]
Name=beamFTL

[AdvOut]
FFAudioTrack=1
FFOutputToFile=true
FTLStreamKey=<REDACTED>
FFURL=ingest-mel.beam.pro
FFABitrate=96
Track1Bitrate=96
```

**Comment by WizardCM** [comment]
Same issue here with the Melbourne Ingest, pressing Start Streaming does nothing.

**Comment by Scrxtchy** [comment]
Open the basic.ini file and replace Mel with Syd
Does that work for you?

Sent from my Mi phone
On Matt Gajownik notifications@github.com, 15 Aug 2016 8:21 PM wrote:

Same issue here with the Melbourne Ingest, pressing Start Streaming does nothing.

**Comment by WizardCM** [comment]
Yes. Hmm.

**Comment by Scrxtchy** [comment]
I'll talk to the platform support staff about it, seems we're in the same boat.
If it's an error with the ingest server, this might not be the correct place to discuss it.
But a more helpful log would be appreciated in tachyon

Sent from my Mi phone
On Matt Gajownik notifications@github.com, 15 Aug 2016 8:23 PM wrote:

Yes. Hmm.

**Comment by WizardCM** [comment]
At least now we know. ¯\_(ツ)_/¯

**Comment by Maximilian-Reuter** [comment]
Well the main thing really is the missing log entries and the fact that instead of correctly failing to connect and aborting in a normal manner tachyon seems to hang and crash if you change any streaming server setting.

**Comment by sslivins** [comment]
all please try the new version of tachyon 1.2.14, if  the issue persists please contact support directly.  these issues are not always related to tachyon so this isn't necessarily the right forum for this.  beam.pro/contact
