### ISSUE TITLE
Tachyon Just Keep Crashing

### ISSUE THREAD

**Issue by WilliamWsyHK** [WatchBeam/ftl-studio#43]
After some short random time (within 5s), the program just crash

[Crash 2016-08-21 10-18-24.txt](https://github.com/WatchBeam/tachyon/files/428637/Crash.2016-08-21.10-18-24.txt)

This does not happened when using Vanilla OBS client. :(

**Comment by sslivins** [comment]
can you provide your obs log as well after the crash happens, they are located in %appdata%\obs-studio\logs

Also would you be able to send this via support at https://beam.pro/contact
