### ISSUE TITLE
Click here to download doesn't do anything

### ISSUE THREAD

**Issue by KSib** [WatchBeam/ftl-studio#44]
When clicking the "Click here to download" link after checking for updates, the link doesn't work. Nothing happens.

Tachyon version: 1.2.12 (64bit, windows)

OS: Windows 10 Pro
Version: 1607
OS Build: 14393.51

Default browser: Chrome Version 52.0.2743.116 m (64-bit)

![image](https://cloud.githubusercontent.com/assets/1589238/17841446/2168c6f4-67de-11e6-9017-ddb187075d6f.png)

**Comment by sslivins** [comment]
sorry, forgot to update the link, should be good to go now
