### ISSUE TITLE
VCRUNTIME140.dll missing when I have

### ISSUE THREAD

**Issue by seekheart** [WatchBeam/ftl-studio#45]
For some reason since upgrading to the latest version of tachyon it seems the VCRUNTIME140.dll error keeps popping back. I have had no problems with the previous version of tachyon and have installed and reinstalled vc_redist.x64 from microsoft.

**Comment by sslivins** [comment]
can you attach your tachyon logs from %appdata%\obs-studio\logs\  just the latest one should be fine

**Comment by sslivins** [comment]
my guess is you will now need the 32 version since i incorporated 32bit game capture support....look for vc_redist.x86.exe.  let me know if that helps and I will update the installer

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by seekheart** [comment]
Problem solved, I installed the 32bit vc and it stopped complaining.

**Comment by sslivins** [comment]
thanks for confirming
