### ISSUE TITLE
Recording Error

### ISSUE THREAD

**Issue by andsim** [WatchBeam/ftl-studio#5]
when i recording i always get this : "An unspecified error occurred while recording."

**Comment by andsim** [comment]
![ftl-studio-2016-04-04](https://cloud.githubusercontent.com/assets/831158/14301554/d197e986-fb66-11e5-83d1-2e2953d4d52a.png)

**Comment by andsim** [comment]
19:29:43.749: CPU Name: AMD FX(tm)-8350 Eight-Core Processor  
19:29:43.749: CPU Speed: 4014MHz
19:29:43.749: Physical Cores: 4, Logical Cores: 8
19:29:43.749: Physical Memory: 24521MB Total, 18323MB Free
19:29:43.749: Windows Version: 10.0 Build 10586 (revision: 0)
19:29:43.749: Aero is Enabled (Aero is always on for windows 8 and above)
19:29:43.762: OBS 2016.04.04 (64bit, windows)
19:29:43.762: ---------------------------------
19:29:43.762: ---------------------------------
19:29:43.762: audio settings reset:
19:29:43.762:   samples per sec: 48000
19:29:43.762:   speakers:        2
19:29:43.769: ---------------------------------
19:29:43.769: Initializing D3D11..
19:29:43.769: Available Video Adapters: 
19:29:43.772:   Adapter 1: AMD Radeon R9 200 Series
19:29:43.772:     Dedicated VRAM: 3202531328
19:29:43.772:     Shared VRAM:    4266311680
19:29:43.772:     output 1: pos={0, 0}, size={1920, 1080}, attached=true
19:29:43.772:     output 2: pos={-1280, 58}, size={1280, 1024}, attached=true
19:29:43.772:     output 3: pos={1920, 0}, size={1920, 1080}, attached=true
19:29:43.778: Loading up D3D11 on adapter AMD Radeon R9 200 Series (0)
19:29:43.791: D3D11 loaded sucessfully, feature level used: 45056
19:29:44.397: ---------------------------------
19:29:44.397: video settings reset:
19:29:44.397:   base resolution:   1920x1080
19:29:44.397:   output resolution: 1280x720
19:29:44.397:   fps:               30/1
19:29:44.397:   format:            I420
19:29:44.401: ---------------------------------
19:29:44.404: Loading module: coreaudio-encoder.dll
19:29:44.405: [CoreAudio encoder]: Failed loading library 'CoreAudioToolbox.dll'
19:29:44.405: [CoreAudio encoder]: Couldn't load CoreAudio AAC encoder
19:29:44.405: ---------------------------------
19:29:44.409: LoadLibrary failed for '../../obs-plugins/64bit/d3dcompiler_43.dll', error: 193
19:29:44.409: Module '../../obs-plugins/64bit/d3dcompiler_43.dll' not found
19:29:44.409: ---------------------------------
19:29:44.412: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/d3dcompiler_47.dll' not found, loading of module failed
19:29:44.413: ---------------------------------
19:29:44.415: Loading module: image-source.dll
19:29:44.415: ---------------------------------
19:29:44.433: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
19:29:44.433: ---------------------------------
19:29:44.440: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
19:29:44.440: ---------------------------------
19:29:44.440: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
19:29:44.440: ---------------------------------
19:29:44.443: Loading module: obs-browser.dll
19:29:44.443: Failed to load 'en-US' text for module: 'obs-browser.dll'
19:29:44.444: ---------------------------------
19:29:44.449: Loading module: obs-ffmpeg.dll
19:29:44.449: ---------------------------------
19:29:44.452: Loading module: obs-filters.dll
19:29:44.452: ---------------------------------
19:29:44.455: Loading module: obs-outputs.dll
19:29:44.456: ---------------------------------
19:29:44.458: Loading module: obs-transitions.dll
19:29:44.458: ---------------------------------
19:29:44.462: Loading module: obs-x264.dll
19:29:44.463: ---------------------------------
19:29:44.465: Loading module: rtmp-services.dll
19:29:44.467: ---------------------------------
19:29:44.470: Loading module: text-freetype2.dll
19:29:44.472: ---------------------------------
19:29:44.476: LoadLibrary failed for '../../obs-plugins/64bit/widevinecdmadapter.dll', error: 126
19:29:44.476: Module '../../obs-plugins/64bit/widevinecdmadapter.dll' not found
19:29:44.476: ---------------------------------
19:29:44.479: Loading module: win-capture.dll
19:29:44.480: load_graphics_offsets: Failed to start 'get-graphics-offsets32.exe'
19:29:44.480: ---------------------------------
19:29:44.484: Loading module: win-decklink.dll
19:29:44.491: No blackmagic support
19:29:44.491: Failed to start search for DeckLink devices
19:29:44.491: ---------------------------------
19:29:44.494: Loading module: win-dshow.dll
19:29:44.510: ---------------------------------
19:29:44.516: Loading module: win-mf.dll
19:29:44.517: [Media Foundation encoder]: Adding Media Foundation AAC Encoder
19:29:44.680: ---------------------------------
19:29:44.683: Loading module: win-wasapi.dll
19:29:44.685: =====================================================================
19:29:44.685: output 'adv_stream' (rtmp_output) created
19:29:44.685: output 'adv_ffmpeg_output' (ffmpeg_output) created
19:29:44.685: encoder 'streaming_h264' (obs_x264) created
19:29:44.685: AAC encoder bitrate mapping:
19:29:44.685:    32 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685:    64 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685:    96 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
19:29:44.685:   128 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
19:29:44.685:   160 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
19:29:44.685:   192 kbit/s: 'Media Foundation AAC Encoder' (mf_aac)
19:29:44.685:   224 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685:   256 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685:   288 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685:   320 kbit/s: 'FFmpeg Default AAC Encoder' (ffmpeg_aac)
19:29:44.685: encoder 'adv_aac0' (mf_aac) created
19:29:44.685: encoder 'adv_aac1' (mf_aac) created
19:29:44.685: encoder 'adv_aac2' (mf_aac) created
19:29:44.685: encoder 'adv_aac3' (mf_aac) created
19:29:44.685: Service '' not found
19:29:44.685: service 'default_service' (rtmp_common) created
19:29:44.687: All scene data cleared
19:29:44.687: ------------------------------------------------
19:29:44.737: WASAPI: Device 'Speakers (Realtek High Definition Audio)' initialized
19:29:44.737: source 'Desktop Audio' (wasapi_output_capture) created
19:29:44.751: WASAPI: Device 'Microphone (Microsoft LifeCam VX-800)' initialized
19:29:44.751: source 'Mic/Aux' (wasapi_input_capture) created
19:29:44.751: source 'Mic/Aux' enabled push-to-talk
19:29:44.783: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds
19:29:44.841: source 'ANDSIMGAMING' (image_source) created
19:29:44.842: source 'full screen game' (scene) created
19:29:44.885: source 'streamjar' (browser_source) created
19:29:44.885: source 'full screen game ' (game_capture) created
19:29:44.885: source 'American Truck Simulator' (scene) created
19:29:44.885: source 'American Truck Simulator ' (game_capture) created
19:29:44.886: source 'full screen game 2' (scene) created
19:29:44.886: source 'BROKEN AGE' (game_capture) created
19:29:44.886: source 'EU' (scene) created
19:29:44.886: source 'EU ' (game_capture) created
19:29:44.989: == Profiler Results =============================
19:29:44.989: run_program_init: 1274.99 ms
19:29:44.989:  ┣OBSApp::AppInit: 1.939 ms
19:29:44.989:  ┃ ┗OBSApp::InitLocale: 1.101 ms
19:29:44.989:  ┗OBSApp::OBSInit: 1247.07 ms
19:29:44.989:    ┣obs_startup: 1.84 ms
19:29:44.989:    ┗OBSBasic::OBSInit: 1226.39 ms
19:29:44.989:      ┣OBSBasic::InitBasicConfig: 0.448 ms
19:29:44.989:      ┣OBSBasic::ResetAudio: 0.966 ms
19:29:44.989:      ┣OBSBasic::ResetVideo: 637.506 ms
19:29:44.989:      ┣OBSBasic::InitOBSCallbacks: 0.022 ms
19:29:44.989:      ┣OBSBasic::InitHotkeys: 0.051 ms
19:29:44.989:      ┣obs_load_all_modules: 283.846 ms
19:29:44.989:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 0.629 ms
19:29:44.989:      ┃ ┣obs_init_module(image-source.dll): 0.004 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-browser.dll): 0.937 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 0.009 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-filters.dll): 0.013 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-outputs.dll): 0.004 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-transitions.dll): 0.01 ms
19:29:44.989:      ┃ ┣obs_init_module(obs-x264.dll): 0.002 ms
19:29:44.989:      ┃ ┣obs_init_module(rtmp-services.dll): 1.342 ms
19:29:44.989:      ┃ ┣obs_init_module(text-freetype2.dll): 1.929 ms
19:29:44.989:      ┃ ┣obs_init_module(win-capture.dll): 0.451 ms
19:29:44.989:      ┃ ┣obs_init_module(win-decklink.dll): 7.31 ms
19:29:44.989:      ┃ ┣obs_init_module(win-dshow.dll): 16.186 ms
19:29:44.989:      ┃ ┣obs_init_module(win-mf.dll): 162.836 ms
19:29:44.989:      ┃ ┣obs_init_module(win-wasapi.dll): 0.008 ms
19:29:44.989:      ┃ ┗reset_win32_symbol_paths: 1.933 ms
19:29:44.989:      ┣OBSBasic::ResetOutputs: 0.623 ms
19:29:44.989:      ┣OBSBasic::CreateHotkeys: 0.022 ms
19:29:44.989:      ┣OBSBasic::InitService: 0.13 ms
19:29:44.989:      ┣OBSBasic::InitPrimitives: 0.374 ms
19:29:44.989:      ┗OBSBasic::Load: 207.53 ms
19:29:44.989: =================================================
19:29:45.236: Update check: last known remote version is 2016.4.4.0
19:30:23.315: Switched to Preview/Program mode
19:30:23.315: ------------------------------------------------
19:30:24.716: Switched to regular Preview mode
19:30:24.717: ------------------------------------------------
19:31:04.689: rtmp-common.c: [initialize_output] Could not find service ''
19:31:04.691: unable to parse streamkey: xxxxxxxx
19:31:04.701: ==== Recording Stop ================================================
19:31:14.533: test ingest-sjc.beam.pro ingest-tor.beam.pro
19:31:14.533: test ingest-tor.beam.pro ingest-tor.beam.pro
19:31:23.064: encoder 'streaming_h264' destroyed
19:31:23.064: encoder 'Track4' destroyed
19:31:23.064: encoder 'Track3' destroyed
19:31:23.064: encoder 'Track2' destroyed
19:31:23.064: encoder 'Track1' destroyed
19:31:23.064: output 'adv_stream' destroyed
19:31:23.065: output 'adv_ffmpeg_output' destroyed
19:31:23.065: output 'adv_stream' (rtmp_output) created
19:31:23.065: output 'adv_ffmpeg_output' (ffmpeg_output) created
19:31:23.065: encoder 'streaming_h264' (obs_x264) created
19:31:23.065: encoder 'adv_aac0' (mf_aac) created
19:31:23.065: encoder 'adv_aac1' (mf_aac) created
19:31:23.065: encoder 'adv_aac2' (mf_aac) created
19:31:23.065: encoder 'adv_aac3' (mf_aac) created
19:31:23.068: Settings changed (outputs)
19:31:23.068: ------------------------------------------------
19:31:24.666: rtmp-common.c: [initialize_output] Could not find service ''
19:31:24.668: unable to parse streamkey: xxxxxxxxx
19:31:24.677: ==== Recording Stop ================================================
19:31:34.631: test ingest-sjc.beam.pro ingest-tor.beam.pro
19:31:34.631: test ingest-tor.beam.pro ingest-tor.beam.pro
19:31:52.590: encoder 'streaming_h264' destroyed
19:31:52.590: encoder 'Track4' destroyed
19:31:52.590: encoder 'Track3' destroyed
19:31:52.590: encoder 'Track2' destroyed
19:31:52.590: encoder 'Track1' destroyed
19:31:52.590: output 'adv_stream' destroyed
19:31:52.590: output 'adv_ffmpeg_output' destroyed
19:31:52.591: output 'adv_stream' (rtmp_output) created
19:31:52.591: output 'adv_ffmpeg_output' (ffmpeg_output) created
19:31:52.591: encoder 'streaming_h264' (obs_x264) created
19:31:52.591: encoder 'adv_aac0' (mf_aac) created
19:31:52.591: encoder 'adv_aac1' (mf_aac) created
19:31:52.591: encoder 'adv_aac2' (mf_aac) created
19:31:52.591: encoder 'adv_aac3' (mf_aac) created
19:31:52.594: Settings changed (general, outputs)
19:31:52.594: ------------------------------------------------
19:32:04.513: encoder 'streaming_h264' destroyed
19:32:04.513: encoder 'adv_aac3' destroyed
19:32:04.513: encoder 'adv_aac2' destroyed
19:32:04.513: encoder 'adv_aac1' destroyed
19:32:04.513: encoder 'adv_aac0' destroyed
19:32:04.513: output 'adv_stream' destroyed
19:32:04.513: output 'adv_ffmpeg_output' destroyed
19:32:04.513: output 'adv_stream' (rtmp_output) created
19:32:04.514: output 'adv_ffmpeg_output' (ffmpeg_output) created
19:32:04.514: encoder 'streaming_h264' (obs_x264) created
19:32:04.514: encoder 'adv_aac0' (mf_aac) created
19:32:04.514: encoder 'adv_aac1' (mf_aac) created
19:32:04.514: encoder 'adv_aac2' (mf_aac) created
19:32:04.514: encoder 'adv_aac3' (mf_aac) created
19:32:04.518: Settings changed (outputs)
19:32:04.518: ------------------------------------------------
19:33:08.469: ---------------------------------
19:33:08.469: video settings reset:
19:33:08.469:   base resolution:   1920x1080
19:33:08.469:   output resolution: 1280x720
19:33:08.469:   fps:               60/1
19:33:08.469:   format:            I420
19:33:08.478: Settings changed (video)
19:33:08.478: ------------------------------------------------
19:33:35.592: ---------------------------------
19:33:35.592: video settings reset:
19:33:35.592:   base resolution:   1920x1080
19:33:35.592:   output resolution: 1280x720
19:33:35.592:   fps:               60/1
19:33:35.592:   format:            NV12
19:33:35.601: Settings changed (advanced)
19:33:35.601: ------------------------------------------------
19:33:37.535: rtmp-common.c: [initialize_output] Could not find service ''
19:33:37.536: unable to parse streamkey: xxxxxxxxxxxxxxxx
19:33:37.545: ==== Recording Stop ================================================
19:33:52.366: rtmp-common.c: [initialize_output] Could not find service ''
19:33:52.368: unable to parse streamkey: xxxxxxxxx
19:33:52.376: ==== Recording Stop ================================================
19:34:01.977: test ingest-sjc.beam.pro ingest-tor.beam.pro
19:34:01.977: test ingest-tor.beam.pro ingest-tor.beam.pro
19:34:30.595: WASAPI: Device 'Speakers (Realtek High Definition Audio)' initialized
19:34:30.595: source 'Desktop Audio' (wasapi_output_capture) created
19:34:30.599: ---------------------------------
19:34:30.599: video settings reset:
19:34:30.599:   base resolution:   1920x1080
19:34:30.599:   output resolution: 1280x720
19:34:30.599:   fps:               60/1
19:34:30.599:   format:            NV12
19:34:30.608: Settings changed (audio, video)
19:34:30.608: ------------------------------------------------
19:34:30.609: source 'Desktop Audio' destroyed
19:34:30.614: WASAPI: Device 'Speakers (Realtek High Definition Audio)' Terminated
19:34:36.475: rtmp-common.c: [initialize_output] Could not find service ''
19:34:36.477: unable to parse streamkey: xxxxxxxxxxxxx
19:34:36.486: ==== Recording Stop ================================================
19:38:58.831: rtmp-common.c: [initialize_output] Could not find service ''
19:38:58.833: unable to parse streamkey: xxxxxxxxxxxxxxx
19:38:58.842: ==== Recording Stop ================================================

**Comment by SkippTekk** [comment]
Did you include the id number? Example 

XXX-streamcodegoeshere

Where the x is your account number.

**Comment by andsim** [comment]
yes i removed the code. sdo i need to XXX- too where XXX?

**Comment by SkippTekk** [comment]
The entire key code. Did you use it as the stream key?

**Comment by andsim** [comment]
okji copy whole code it working, could u reword that make more detail of the error please

**Comment by SkippTekk** [comment]
I cant. Im just a random person trying to help you out. I dont work nor know any of the code.

**Comment by andsim** [comment]
developer need to

**Comment by MattJustMatt** [comment]
@NCommander

**Comment by NCommander** [comment]
I'm fixing the code to be more specific when this goes boom. It will be in the next release later today

**Comment by karljakober** [comment]
This happened to me when I was using an audio output device that wasnt enabled through windows , Virtual audio cable, windows 10. A more informative error would have been nice!
