### ISSUE TITLE
device_copy_texture (GL) failed

### ISSUE THREAD

**Issue by ghost** [WatchBeam/ftl-studio#51]
```
error: glCopyImageSubData failed, glGetError returned 0x502
error: device_copy_texture (GL) failed
```

I get this error when i try to Window Capute the termianl (Terminator, Ubuntu 16 LTS), is there any workaround?

**Comment by Maximilian-Reuter** [comment]
do you get the same issue using OBS ?

**Comment by ghost** [comment]
@Maximilian-Reuter yes, in OBS too.

**Comment by Maximilian-Reuter** [comment]
well that's easy then ;) you have to post this issue there since Tachyon is just a modified version of OBS.

Their issue tracker is located here : https://obsproject.com/mantis

**Comment by ghost** [comment]
@Maximilian-Reuter thought that Tachyon re-written is, since OBS is not that good. Anyway, i can't even stream :D

**Comment by Maximilian-Reuter** [comment]
Nope :D Tachyon is OBS with ftl support. It even uses the same config folders and files.

I mean seeing as you are on Ubuntu, you could always build the project from source...
The latest release is more than a month old afterall.

https://github.com/jp9000/obs-studio
