### ISSUE TITLE
Can't launch on Mac OS X 10.10 El Capitan

### ISSUE THREAD

**Issue by myraiganai** [WatchBeam/ftl-studio#58]
Tachyon crashes when opening.
When reopening it says **
Failed to find locale/enUSini**

Also, an app icon in the Launchpad is missing.

![screenshot 2016-10-29 06 19 23](https://cloud.githubusercontent.com/assets/16563020/19827128/acb3737a-9d9f-11e6-8451-b68f6fb1f4a2.png)

**Comment by DarioJames** [comment]
Issue also occurs on macOS Sierra 10.12.1

**Comment by DarioJames** [comment]
Workaround was to revert to 1.2.11

**Comment by narcogen** [comment]
Workaround no longer viable as Beam is blocking old versions of Tachyon.

**Comment by DarioJames** [comment]
OBS +FTL .20 is out for Mac....works much better than any of the Tachyon
builds did. Even for older Macs.
