### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by EnZedBob** [WatchBeam/ftl-studio#6]
Downloaded the tachyon_setup_20160412.exe and it got removed by windows defender for containing a "Trojan: Win32/Fathale.B!plock".
I allowed it and ran it through virustotal with this result https://www.virustotal.com/en/file/318dfd94d021510f6e99d96535f2d78ceb93e04705f0456f30da09c56a99300e/analysis/1460495479/

Thought it was best to let you guys know about it.

**Comment by MattJustMatt** [comment]
:( well that's annoying. CC'ing @NCommander

**Comment by MrAdder** [comment]
I can confirm this is a False Positive

**Comment by KSib** [comment]
Avast flags it as suspicious well.

![image](https://cloud.githubusercontent.com/assets/1589238/15347811/6a347f6c-1c8a-11e6-98ae-fda139d4f9c0.png)
