### ISSUE TITLE
Windows 10: Cannot Launch Tachyon v1.2.16 

### ISSUE THREAD

**Issue by Kirschie** [WatchBeam/ftl-studio#66]
When launching the application I get a "This app cannot run on your PC". I have an option to chose OK to close the error. There are not errors in event logs.

**System Information:**
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-L6G2QCU
System Manufacturer	Hewlett-Packard
System Model	HP EliteBook 6930p
System Type	X86-based PC
System SKU	KS082UT#ABA
Processor	Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz, 2401 Mhz, 2 Core(s), 2 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard 68PCD Ver. F.0E, 12/15/2008
SMBIOS Version	2.4
Embedded Controller Version	87.22
BIOS Mode	Legacy
BaseBoard Manufacturer	Hewlett-Packard
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	DESKTOP-L6G2QCU\johnl
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	4.00 GB
Total Physical Memory	3.00 GB
Available Physical Memory	607 MB
Total Virtual Memory	4.62 GB
Available Virtual Memory	1.19 GB
Page File Space	1.63 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	No
Hyper-V - Virtualization Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes

**Comment by SanokKule** [comment]
If you using 32bit OS, thats a problem.
Tachyon doesn't support 32bit systems.
At least I think so.

**Comment by Maximilian-Reuter** [comment]
or simply use this as it's the currently developed version https://github.com/WatchBeam/obs-studio-ftl/releases

**Comment by Kirschie** [comment]
Thanks guys. That's what I figured.
